### ISSUE TITLE
Formatting of Grey Goshawk text onward broken

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#130] opened 2019-03-22 03:06 UTC
The book still builds at the moment, so I've been making edits to the body of the Atlas so that we don't just stop progress while we're trying to resolve #129. Oddly, every species in the book from Grey Goshawk onward is centre aligned rather than justified, and there's some other funky markdown (or tex?) stuff happening too:

![image](https://user-images.githubusercontent.com/44354406/54798187-2d020c80-4ca3-11e9-8c8c-be2afd1ebb01.png)

I will attempt to resolve this by working out what about the GG text is different, but putting this up here in case I can't work it out.

**Comment by Louis-Backstrom** [comment] 2019-03-22 05:24
This is fixed in 79075e6. Initially I'd put Rmd italics ("_Accipiter_") in the caption, which for whatever reason had sent the formatting all wonky in tex. Currently Accipiter is just left as is in the caption, but I'd like to italicise it (or non-italicise it, seeing as the whole caption is italicised) somehow still. Closing this for now, but if @jeffreyhanson has any ideas on how to do that without breaking either the website or the book?

**Comment by jeffreyhanson** [comment] 2019-03-22 10:44
Hmm, you might have to escape the `"` symbols, i.e. put `\"` instead

**Comment by Louis-Backstrom** [comment] 2019-03-22 11:16
wouldn't escaping the \_ just present the text as \_Accipiter\_ instead of _Accipiter_? 

(Probably should have clarified, I don't want inverted commas, I just want italicised text (as per genus name conventions), but using markdown's standard underscore notation breaks the formatting as the caption is nested within a function)

**Comment by jeffreyhanson** [comment] 2019-03-22 22:03
Oh right - yes, I misunderstood - sorry. The problem is that the atlas manually handles the formatting of the text in the captions to ensure consistency between the pdf and the website. That is, it actually writes the html and latex code, instead of relying on pandoc to do the conversion (which is what happens for most other text in the atlas), and so markdown syntax doesn't actually apply. So, I would need to update the https://github.com/bird-team/brisbane-bird-atlas/blob/master/code/functions/render_species_profile.R file so that it can recognise basic markdown formatting. This is not trivial - but I agree that it's important to add this functionality.

**Comment by Louis-Backstrom** [comment] 2019-03-22 23:06
Alright, that sounds like a low priority issue - I'll reopen this but hibernate it so we can come back to it later.

**Comment by Louis-Backstrom** [comment] 2019-04-10 10:25
Tried a bunch of different attempts at a simple solution to no avail - it seems like it'll have to be a deeper change in the underlying code to get the functionality.

**Comment by jeffreyhanson** [comment] 2019-06-28 16:24
I've just pushed an attempt to support italics/bold text in the captions. Let's see if it works when the pdf finishes rebuilding. Note that it assumes that all underscores and asterisks have spaces around them (e.g. `this is regular text, _this is italics text_ . In other words, starting italics/bold text mid-word (e.g. `regulartext_italicstext_`) will cause problems.

**Comment by Louis-Backstrom** [comment] 2019-06-29 06:02
Hmmm, this doesn't seem to have worked:

![image](https://user-images.githubusercontent.com/44354406/60380316-0fed8e80-9a87-11e9-832f-efaec035833a.png)

and neither on the website:

![image](https://user-images.githubusercontent.com/44354406/60380319-1976f680-9a87-11e9-9e58-c8cb0de98bc0.png)

What's more, the formatting of the rest of the text in the book appears to be kinda broken - I don't know how new/old this is but I think we want justified text in the columns (not center aligned) and left aligned text in the titles?
![image](https://user-images.githubusercontent.com/44354406/60380326-2e538a00-9a87-11e9-80e5-3cc752a18ac9.png)

**Comment by jeffreyhanson** [comment] 2019-06-29 15:53
Ok - thanks for checking this. I've just pushed another attempt at fixing this - let's see if it works when the rebuild finishes.

Yeah - that formatting isn't right, I don't know why that's happened. Let's see if it persists.

**Comment by jeffreyhanson** [comment] 2019-06-29 16:20
It looks like the formatting issue in the pdf is caused by a `%` symbol in the caption (note this doesn't affect `%` symbols in the main text of an Rmarkdown document). This is because `%` symbols are treated as comments in Latex, meaning that the following text these symbols are ignored which can cause issues. I'll update the code so that it automagically handles `%` symbols correctly.

**Comment by jeffreyhanson** [comment] 2019-06-29 16:22
Also, I just realised the text for figure captions are formatted to be italics. So if the code for specifying italics is working then we won't actually notice any difference since the whole caption, including the text we manually specify as italics, will be italics.

**Comment by jeffreyhanson** [comment] 2019-06-29 16:46
Yeah, it looks like the text justification/formatting issue was fixed by 2691b30.

**Comment by Louis-Backstrom** [comment] 2019-06-30 00:58
Is it possible to make it such that "double italicising" (ie "italics" inside the caption) reverts back to normal text? This seems to be the convention elsewhere when writing species names and the like - could we achieve that here easily?

I seem to recall from my brief experiments with latex that instead of "italicising" text you can emphasize it (or something similarly named), and one level of emphasis is italics but two levels is normal text? Or something?

**Comment by jeffreyhanson** [comment] 2019-06-30 10:25
IIRC the convention for species/taxonomic names in paragraphs of italics text is to underline them. However, markdown doesn't have any syntax for underlines so we would have to invent something using characters we don't think we would ever use in normal text (e.g. `$$this sentence is underlined$$`, or `@@this sentence is underlined@@`). What do you think? Do you have any ideas for which character we should reserve for underlining text?

**Comment by Louis-Backstrom** [comment] 2019-06-30 23:51
maybe ||this sentence is underlined|| ? It doesn't really matter too much, I doubt we'll use double symbols very much ever.

**Comment by jeffreyhanson** [comment] 2019-07-01 08:21
Yeah good idea - I'll try and implement this today.

**Comment by jeffreyhanson** [comment] 2019-07-01 09:06
Ok, I'm closing this now because we have underlining in both the pdf and html versions of the atlas (https://brisbanebirds.com/grey-goshawk-accipiter-novaehollandiae.html#grey-goshawk-accipiter-novaehollandiae).

**Closed as completed by jeffreyhanson** 2019-07-01 09:06 UTC
Labels: style, hibernated

**Comment by Louis-Backstrom** [comment] 2019-07-01 22:42
Looks fantastic, thanks Jeff
