### ISSUE TITLE
No. of records now exceeding excel row limit

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#120] opened 2019-03-02 00:32 UTC
I doubt it has any effect on the processing / running of the Atlas but as of the 2019Jan eBird release there's now more records than excel can show (only by about 10,000 at the moment but that will definitely increase quickly). I assume R etc. don't have a similar limit?

**Comment by jeffreyhanson** [comment] 2019-03-02 14:21
Thanks for raising this issue. Yeah, I don't think this shouldn't be a problem. In theory, this should only be a problem if someone were to first open the raw eBird data in Excel and then save it   --- but sometimes Excel will overwrite files even if you don't actually tell it so save the file, so I would avoid this just in case. I'll close this issue since I don't think it's a problem, but please reopen this if you start noticing strange things happening and think it might be caused by this.

**Closed as completed by jeffreyhanson** 2019-03-02 14:21 UTC
Labels: data
